#!/usr/bin/env bash
# Configure HAproxy to automatically redirect HTTP traffic to HTTPS.


global
    ssl-default-bind-options ssl-min-ver TLSv1.2

frontend eazylinktechnology_frontend
	bind *:80
	bind *:443 ssl crt /etc/haproxy/certs/eazylinktechnology.tech.pem
	http-request redirect scheme https code 301 unless { ssl_fc }
	default_backend eazylinktechnology_backend

backend eazylinktechnology_backend
	balance roundrobin
	server 156813-web-01 100.25.193.56:80 check
	server 156813-web-02 18.210.19.239:80 check
