#!/usr/bin/env bash

# Update package lists
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Create a new default configuration file
sudo rm /etc/nginx/sites-enabled/default
sudo touch /etc/nginx/sites-enabled/default

# Add configuration to the new default file
echo "Hello World!" > /var/www/html/index.nginx-debian.html
# Test configuration and restart nginx
sudo nginx -t && sudo /etc/init.d/nginx restart
