#!/usr/bin/env bash
# Install Nginx and the init file have only a message
sudo apt install update -y
sudo apt install upgrade -y
sudo apt install nginx -y
sudo service nginx start
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
