#!/usr/bin/env bash
# write a Bash script that configures a new Ubuntu machine to respect above 
# requirements (this script will be run on the server itself)
STRING="Hello World!"
REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ; \n\t}\n"
FILE="/etc/nginx/sites-available/default"
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "$STRING" > /var/www/html/index.nginx-debian.html
sudo sed -i "37i\ $REDIRECT" "$FILE"
sudo service nginx restart
