#!/usr/bin/env bash

# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get install nginx -y

# Replace default Nginx configuration with custom configuration
sudo echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        try_files $uri $uri/ =404;
    }
    # Custom HTTP response header
    add_header X-Served-By \$hostname;
}" > /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo systemctl restart nginx
