#!/usr/bin/env bash
# Script to configure Nginx with custom HTTP response header

# Install Nginx
apt-get update
apt-get install -y nginx

# Configure Nginx to include custom header
custom_header='add_header X-Served-By $hostname;'
sed -i "/listen \[::\]:80 default_server;/a \\\t$custom_header" /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
