#!/usr/bin/env bash
# configures a new HAproxy as a load balancer
# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*
# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend eazylinktechnology.tech
        bind 0:80
        default_backend web_servers
backend web_servers
        balance roundrobin
           server 156813-web-01 100.24.237.31:80 check
           server 156813-web-02 100.25.129.126:80 check
' >> /etc/haproxy/haproxy.cfg
# Restart HAproxy service
service haproxy restart
