#!/usr/bin/env bash

# This is script prints "Holbertob School" 10 times
word='Holberton School'
#shellcheck disable=SC2034 # unused variable left to hold count values
for i in {1..10}; do echo "$word"; done
